sudo: required
dist: trusty
language: node_js
node_js:
- '8'
env:
  global:
  - BROWSER_STACK_USERNAME: bugsnagplatforms1
  - secure: "QBTKMeq/xlkbH/x3dhgeKhnowmZ635B7RFHydt6W3TiO0dUO4kUvWWgh9a9TMtd1OLyvLu0CF0X49uhx0z2iiDN7Fu+NDR18fkCfE+26eWBCVv6e3S++2hEwwgTSEBq+dC7/a0JPpufPtW+x7NqaVZPouYJFWOv9N/WutueE8SprS1OQcfv4BMsrLQbNPt1g5O21Q4Zk3nSDDjw2ph4el9c2Sajz73p+rt5SubiZgNHPKMeel7v5VkAeVwGoE+m68tljcxGZpnQxPgLNujx2O1L/XqUILgdSaLHzcmf/cphxkBEZYMpFk3qEpTcyHbaL4b8lBRc4jD6COdIJijSibeAVdn+TPZjSCJ4Z5TzRX6QZ+uXCT+HGkucPlB1ark0wJJsd40rFeZD4Gechu9OCFL3aFJ+tSi+M+Xg5ADSBNxKHUDeo/g6kTHdE7aSsZu9/QJ1c7BsZRuTEdCXIQ0OcxMj0691WzNAewY0hHSpeOP7Ul03ULoYXrQbGNkbFaeUS+8rdUo4YFrvWP7W3PUaLoAO2EW+Uyqh6TqqUHFCaURzMA9F7vVQeZvoOXKojG4IMbAZen+rtUPR+lnA9JuGcS8LL6xqKKimlCEQBWtmgER0Bk/hBV9hIp8aTcFtPhh4ym1Y7XnhJEfyD/seSSB/j3IoM/rnrcH/v5JvLtilN+fI="
addons:
  chrome: stable
  browserstack:
    username: bugsnagplatforms1
    access_key:
     secure: "f/b4QokddI5ZJ8WBHFy1s+NHOP7+2/fvmKWsUqYaW/XLNDcrSGVcMlCzWSNsbQxLEofiJhrpoSXE1a9IivOqNQbnUvdLxgF/3UVFKXsIGJTG1ofru91lYjVGnLFETcv6bvbYRAZ1nYAz6Dkl2zM3uUIqzy7VI1Eu7lQO8alnA4Edn9UnmakXeIxl5gvSzjN8bhsI7nBb27CrKwU2ssWmpcVDO4Ggq+LEuR4q1Sk1AqWXhWFjqncuyuEDSD3zo4JjwP57ZWgh4NfuU3VKaiHXRhBrPHQwtiRtGVq1m1CbACUSIsOHDxC0xoos0Dl0ayjASbDWsrdDNN9uLcnWfV6tMN2/1dSApENSb7SqntTNWnQds8Er9ss2oxZUiewj6lM3t5u3aAt1VZpbuqf3PlgzsspEMUbXPbZw2hi7vRclEugp5aPExeAf8ZEr6QqZTaTixsfucrN0Gw45awr8VXd/jc9P1z++Lrk6b+oWUppUezUFWxGXkT4HI3FhUNQiphGl0xJPIQPlu5sT7nBKo8XJ8cvTYpl3t6kDuDRk5VbxlQpiNrvUHnr2Jjri0iPrdchjOSjjH/0Li9GsEpfIqPCAwSocWEIztDLKTBf/NF/5L2tZwKk0vcYPwgemeclnJFaa/lOWtg0bYa2s18yLO/MqBIAJjpMzZxApwpFAX8h1hE8="
script:
- if [[ $BROWSER_STACK_ACCESS_KEY ]]; then npm run test; else npm run test:basic;
  fi
