name: "unit test"

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 8
      - name: Checkout PR branch
        uses: actions/checkout@v1
      - run: npm install
      - run: npm test
