name: "unit test"

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [12, 14, 16, 18, 20, 22]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout PR branch
        uses: actions/checkout@v1
      - run: npm install
      - run: npm test
