name: "unit test"

on: push

env:
  BROWSERSTACK_ACCESS_KEY: "${{ secrets.BROWSERSTACK_ACCESS_KEY }}"
  BROWSERSTACK_USERNAME: "${{ secrets.BROWSERSTACK_USERNAME }}"

jobs:
  test:
    runs-on: ubuntu-20.04
    environment: CI
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 8
      - name: Checkout PR branch
        uses: actions/checkout@v1
      - run: npm install
      - run: npm test
